### ISSUE TITLE
THE "FORK YOU" LINK IS BROKEN

### ISSUE THREAD

**Issue by TimPietrusky** [bullgit/SCREAM.CSS#1]
THE FORKING "FORK YOU" LINK INSIDE THE README:MD IS BROKEN! SO FORK YOU; GITCH!

**Comment by reimersjan** [comment]
FIXED THAT https://github.com/bullgit/SCREAM.CSS/commit/091cd9d12c9bdac433669feffb3d6230c365053a

FORK YOURSELF

**Comment by TimPietrusky** [comment]
FORK YOU TOO; SIR!
